### ISSUE TITLE
Tab bar

### ISSUE THREAD

**Issue by rugk** [kurogetsusai/firefox-gnome-theme#1]
> Also the menu bar is below the tab bar (things are flipped upside down to move the tabs below the URL bar). That's pretty shit, but I haven't figured out how to move the tab bar without flipping everything else yet and I don't use the bookmark bar anyway so I'm fine with that.

Did you have a look at https://github.com/Aris-t2/CustomCSSforFx/? They also have some "experimental" code to move "tabs not on top".

**Comment by lunakurame** [comment]
I've seen that repo before, but didn't notice they move the tab bar to the bottom too. I see they are using the `-moz-box-ordinal-group` CSS property instead of `-moz-box-direction: reverse`, and it moves just the tab bar without flipping everything else. I'll fix the code soon, thanks for letting me know!
