### ISSUE TITLE
Automatically select dark or light theme

### ISSUE THREAD

**Issue by garrett** [kurogetsusai/firefox-gnome-theme#12]
Instead of editing the CSS to add an include, automatically select the dark or light theme.

It can probably be keyed based on the window element with a specific attribute like:

```css
window[lwthemetextcolor="bright"]
```
...for dark mode

and

```css
window:not([lwthemetextcolor="bright"])
```
...for light mode.

There might need to be more matches; I didn't test this for native light/dark themes, only the switch in customize.

**Comment by lunakurame** [comment]
That would certainly be useful, but at this point we already have 3 theme variants (and there will be more, because of different GNOME versions), as well as a few extra options like client-side decorations settings and symbolic icons, which means some options would have to be enabled in the CSS file anyway. Besides, switching those built-in themes currently breaks too much of existing code and it wouldn't be possible to switch between different variants without restarting Firefox anyway, because that theme relies on GTK styles for popup menus, text colors in some places, icon colors, etc. I just tested it and it doesn't seem to work for native theme variants, `window` doesn't have any attribute indicating current GTK theme variant either. So for now I'm not gonna implement this, maybe in the future if we manage to make it more config-less (assuming it's possible to detect or ditch GTK styles).

By the way, our existing config evolved recently, thanks to issue #14 it's possible to preserve theme configuration between updates by saving it to the `customChrome.css` file, so I think it became slightly less annoying.
