### ISSUE TITLE
Close Button Is Misaligned with CSD

### ISSUE THREAD

**Issue by Saroufim** [kurogetsusai/firefox-gnome-theme#25]
The close button on Fedora 27 with Firefox 58 + CSD is misaligned with the rest of the HeaderBar. 
![csd-firefox-issue](https://user-images.githubusercontent.com/4712288/35932250-e0fcfac4-0c3f-11e8-815a-ac3ade5a07cd.png)
This is persistent with all sizes of the CSD bar and with both light and dark themes.

**Comment by lunakurame** [comment]
There currently are 2 versions of that CSD style sheet, for FF 57 with Fedora's patch and for FF 59. I'll fix it for FF 58 too, but I need to finish merging changes from issue #21 first. Could you check if enabling the version for FF 59 works for FF 58 on Fedora? It might work, because I remember other styles for FF 57 were misaligned for both FF 58 and 59 too.
```css
/* Enable CSD for Firefox 59 */
@import "ui/csd.css"; /**/
/* Enable CSD for Firefox 57 (Fedora only) */
/*@import "ui/fedora-csd.css"; /**/
```
Let me know if it works. If not, then https://github.com/smithfred/firefox-gnome-theme-3.26-layer might have some workarounds for now.

**Comment by Saroufim** [comment]
CSD for Firefox 59 works perfectly on Fedora 27 with Firefox 58. Thank you very much. This theme is a treasure. Thanks for making it.

**Comment by lunakurame** [comment]
I'm glad I could help (and I'm sure other contributors are too :p). Just added info that FF 58 users can use FF 59 CSD styles to the `userChrome.css` file (commit 53e214aefa0058ab7af734e4912605d4dafd642d), so others know about it. Thanks for testing it!
