### ISSUE TITLE
Firefox 61: Titlebar is cut on the top

### ISSUE THREAD

**Issue by Saroufim** [kurogetsusai/firefox-gnome-theme#29]
The titlebar margin is cut short from the top on Firefox 60+. Previously, adjusting the height margin value from fedora-css fixed that but it no longer does after the latest update. 

![captura de pantalla de 2018-03-31 14-48-00](https://user-images.githubusercontent.com/4712288/38162934-83807448-34f3-11e8-8b5b-db2c55a396c6.png)

**Comment by lunakurame** [comment]
I just updated this repo to FF 58 (yeah, we're kinda behind Mozilla...), I'll update it to FF 59 in like 2 days if everything works. I see CSD works ok on FF 59 alpha, but FF 59 stable doesn't seem to have CSD support at all, which kinda surprised me since it was working well for a long time now, idk why would they remove it. Anyway, that `fedora-csd.css` file was supposed to be only for FF 57 with Fedora's CSD patch, I'll add something similar for FF 60 to fix it soon, thanks for reporting this issue! :D

**Comment by lunakurame** [comment]
I added a quick fix, for now please enable `experimental-ff-60-csd.css` instead of `csd.css` and it should work. I'll merge those files when FF 60 stable comes out. Also this solution isn't perfect yet, it glitches out when the `hide-single-tab.css` module is enabled. I can't figure out how to fix it now, I'll take a look at it again after fixing other bugs in FF 59 stable.

**Comment by Saroufim** [comment]
The result is exactly as you described it. The headerbar is fixed again but single tabs are no longer hidden. That's something I can live with at least. Thank you very much!

**Comment by rafaelmardojai** [comment]
My fix for FF 61 is working nice with hidden tab.

**Comment by lunakurame** [comment]
Thanks @rafaelmardojai, your changes look perfect for me and they work with `hide-single-tab.css`, thank you for fixing our CSD again! :D

**Comment by Saroufim** [comment]
Thank a lot to the both of you!
