### ISSUE TITLE
No rounded corners on the headerbar (FF 60/61)

### ISSUE THREAD

**Issue by HunterGraubard** [kurogetsusai/firefox-gnome-theme#32]
Thank you for your great work on this. This is wonderful. For the most part it works great, but I do have one minor issue:

I've tested it on both Firefox beta (60) and nightly (61), with the browser's titlebar turned off. In both cases the headerbar does not have rounded corners. They're just sharp, rectangular corners. The screenshots I've seen suggest that there should be rounded corners, so I believe this is a bug. I'm using the `experimental-ff-60-csd.css` file.

**Comment by rafaelmardojai** [comment]
That's a Firefox issue with CSD. 
Nothing we can do at all.

**Comment by HunterGraubard** [comment]
Okay, thanks for clearing that up. Hopefully they'll improve it then.

Edit: But I did see screenshots of it working with rounded corners. What was that then? Some kind of Fedora patch?

**Comment by rafaelmardojai** [comment]
Yeah, you can found the bug on Firefox here [https://bugzilla.mozilla.org/show_bug.cgi?id=1408360](https://bugzilla.mozilla.org/show_bug.cgi?id=1408360).

**Comment by rafaelmardojai** [comment]
@HunterGraubard Yes Firefox 57/58 patched by fedora used to work fine. But now current stable (59) on Fedora has the same bug (they now use upstream CSD).

**Comment by lunakurame** [comment]
Actually I was testing FF 59 on Fedora two days ago and I tried to fix it, but nothing worked. I thought it's just because I was running it on a virtual machine, but looks like it's an actual bug. Thanks for that link, Rafael.

While we can't add rounded corners to the window, we technically can add it to the headerbar. For now I added this dirty hack (e770289), it doesn't solve the problem, but I think it looks slightly better. This part: `window:not([width="960"]):not([height="1053"])` is supposed to **not** add rounded corners when the window is vertically maximized and takes half the screen, since that's the standard GTK behavior. It works only for 1920x1080, other resolutions are gonna have rounded corners because I don't know the exact numbers for them.

Result:
![screenshots](https://i.imgur.com/jI55RPM.png)

It's still ugly, but it's the best I can do now. I'll remove it once Mozilla fixes that bug.

**Comment by smithfred** [comment]
Firefox 64 (at least on Fedora) has this bug fixed in the native theme. Unfortunately it seems to rely on a (new?) -moz-appearance, which breaks e.g. the background colour of the close button, at least on my frankenstein combination of this and my fixes "layer" - setting -moz-appearance to none for the close container squares that corner again.

But should be fixable now.
