### ISSUE TITLE
Back button slightly larger than forward button (blurry back icon)

### ISSUE THREAD

**Issue by YarnSphere** [kurogetsusai/firefox-gnome-theme#41]
This is a minor issue but, as you can see, the back button is slightly larger than the forward one, making the icon appear blurry:
![screenshot from 2018-05-18 15-11-05](https://user-images.githubusercontent.com/8314616/40236518-20b722e0-5aae-11e8-9a71-8a509c8b36ef.png)

I'm not sure if this only happens to me. My monitor has a 1920:1080 ratio; the issue exists independently of the size of the Firefox window. Using latest `master` under FF 60.0.

Once again, thank you for your work!

**Comment by lunakurame** [comment]
Oh god, that bug again. It was already fixed for FF 57, then again for FF 58, then it actually worked without changes for FF 59 and now it's broken again: #17. It's because the back button is bigger in Firefox' default theme to implement that fancy circle around it. Mozilla keeps changing the styles every release, so our overrides stop working and the icon scales improperly. I'll fix it in a second since I already found the culprit. Thanks for reporting it!

**Comment by YarnSphere** [comment]
My bad for opening a new issue, I should have browsed through the closed ones beforehand!
But I'm glad that it's easy to fix! It's one of those small issues that drive you nuts after you notice them for the first time! :D

**Comment by lunakurame** [comment]
Yeah, small issues you notice, fix, and then they come back a hundred times. :P It's okay tho, the icon or the whole button is usually just forced to scale to some arbitrary size, so unsetting those rules fixes the problem. Just pushed a fix to `master`, works fine for me now.

**Comment by YarnSphere** [comment]
Works fine for me too! Thank you for the quick fix!
